import { useEffect, useState } from "react";
import { Text, View } from "react-native";
import { Button, Card, ErrorBanner, Header, Screen, SectionHeader, uiStyles } from "@/components/ui";
import { useAppData } from "@/context/AppDataContext";
import { fetchSpaceWeather, SpaceWeatherSnapshot } from "@/services/spaceWeather";
import { createThemedStyles, spacing } from "@/theme";

export default function SpaceWeatherScreen() {
  const { observer } = useAppData(); const [data, setData] = useState<SpaceWeatherSnapshot | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(true);
  const load = async () => { setBusy(true); setError(""); try { setData(await fetchSpaceWeather(observer)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Space-weather data could not be loaded."); } finally { setBusy(false); } };
  useEffect(() => { let active = true; fetchSpaceWeather(observer).then((value) => { if (active) setData(value); }).catch((reason) => { if (active) setError(reason instanceof Error ? reason.message : "Space-weather data could not be loaded."); }).finally(() => { if (active) setBusy(false); }); return () => { active = false; }; }, [observer]); const aurora = data?.auroraProbability ?? 0; const rating = aurora >= 40 ? "STRONG CHANCE" : aurora >= 15 ? "WATCH THE NORTH" : "LOW LOCALLY";
  return <Screen><Header eyebrow="NOAA live conditions" title="Aurora & Space Weather" />{error ? <ErrorBanner message={error} /> : null}<Card style={styles.hero}><Text style={styles.kicker}>AURORA AT {observer.label.toUpperCase()}</Text><Text style={styles.probability}>{data?.auroraProbability == null ? "—" : `${Math.round(aurora)}%`}</Text><Text style={styles.rating}>{data ? rating : busy ? "LOADING" : "NOAA UNAVAILABLE"}</Text><Text style={uiStyles.muted}>Nearest OVATION forecast-grid probability. Darkness, cloud and a clear northern horizon still decide whether it is photographable.</Text></Card>
    <View style={styles.grid}><Metric label="PLANETARY KP" value={data ? data.kp.toFixed(1) : "—"} note={data && data.kp >= 5 ? "Geomagnetic storm level" : "Current index"} /><Metric label="SOLAR WIND" value={data?.solarWindSpeed ? `${Math.round(data.solarWindSpeed)} km/s` : "—"} note="Higher can enhance activity" /><Metric label="IMF BZ" value={data?.bz != null ? `${data.bz.toFixed(1)} nT` : "—"} note={data && data.bz != null && data.bz < 0 ? "Southward: favourable" : "Northward/neutral"} /></View>
    <Button title={busy ? "Refreshing NOAA data…" : "Refresh space weather"} onPress={() => void load()} disabled={busy} /><SectionHeader title="Photographer’s readout" /><Card><Text style={uiStyles.body}>{data && data.kp >= 5 ? "Charge batteries and scout a dark northern view. Use a wide lens, start around f/2–f/2.8, 1–8 seconds and adjust ISO to preserve curtain colour." : "Conditions are currently quiet to moderate. Keep alerts in mind, but plan ordinary deep-sky imaging unless the Bz turns strongly southward and Kp rises."}</Text><Text style={uiStyles.muted}>{data ? `Forecast ${new Date(data.observedAt).toLocaleString()}${data.cached ? " · cached reading" : " · live NOAA reading"}` : "Waiting for NOAA"}</Text></Card><Text style={styles.credit}>Data: NOAA Space Weather Prediction Center. Forecasts are estimates, not guarantees of visible aurora.</Text></Screen>;
}
function Metric({ label, value, note }: { label: string; value: string; note: string }) { return <Card style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricNote}>{note}</Text></Card>; }
const styles = createThemedStyles((colors) => ({ hero: { alignItems: "center", borderColor: colors.gold }, kicker: { color: colors.gold, fontSize: 10, fontWeight: "900", letterSpacing: 1.1 }, probability: { color: colors.text, fontSize: 56, fontWeight: "900" }, rating: { color: colors.success, fontWeight: "900", letterSpacing: 1.5 }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, metric: { width: "47%", flexGrow: 1, minHeight: 120 }, metricLabel: { color: colors.muted, fontSize: 9, fontWeight: "900" }, metricValue: { color: colors.gold, fontSize: 22, fontWeight: "900" }, metricNote: { color: colors.text, fontSize: 11 }, credit: { color: colors.muted, fontSize: 10, textAlign: "center", lineHeight: 15 } }));
