import { useLocalSearchParams, useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Card, EmptyState, Screen, uiStyles } from '@/components/ui';
import { targets } from '@/data/targets';
import { useAppData } from '@/context/AppDataContext';
import { colors, radius, spacing } from '@/theme';

export default function TargetDetailScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const router = useRouter(); const { favourites, toggleFavourite } = useAppData(); const target = targets.find((item) => item.id === id);
  if (!target) return <Screen><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Catalogue</Text></Pressable><EmptyState title="Target not found" message="This catalogue entry is unavailable." /></Screen>;
  return <Screen><View style={styles.nav}><Pressable onPress={() => router.back()}><Text style={styles.back}>‹ Catalogue</Text></Pressable><Pressable onPress={() => void toggleFavourite(target.id)}><Text style={[styles.star, favourites.includes(target.id) && { color: colors.gold }]}>★</Text></Pressable></View><View><Text style={styles.catalogue}>{target.identifiers.join(' · ')}</Text><Text style={uiStyles.title}>{target.name}</Text><Text style={uiStyles.muted}>{target.type} in {target.constellation}</Text></View><Card><View style={styles.grid}><Datum label="RIGHT ASCENSION" value={target.ra} /><Datum label="DECLINATION" value={target.dec} /><Datum label="APPARENT SIZE" value={target.apparentSize} /><Datum label="DIFFICULTY" value={target.difficulty} /></View></Card><View><Text style={styles.heading}>Recommended filters</Text><View style={styles.filterRow}>{target.filters.map((filter) => <Text key={filter} style={styles.filter}>{filter}</Text>)}</View></View><Card><Text style={styles.heading}>About this target</Text><Text style={uiStyles.body}>{target.description}</Text></Card><Card><Text style={styles.heading}>Imaging notes</Text><Text style={uiStyles.body}>{target.imagingNotes}</Text></Card></Screen>;
}
function Datum({ label, value }: { label: string; value: string }) { return <View style={styles.datum}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></View>; }
const styles = StyleSheet.create({ nav: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, back: { color: colors.blue, fontSize: 16, fontWeight: '600' }, star: { color: colors.border, fontSize: 27 }, catalogue: { color: colors.gold, fontSize: 12, fontWeight: '800', letterSpacing: 1, marginBottom: 5 }, grid: { flexDirection: 'row', flexWrap: 'wrap', rowGap: spacing.lg }, datum: { width: '50%' }, label: { color: colors.muted, fontSize: 10, fontWeight: '700', letterSpacing: 1 }, value: { color: colors.text, fontSize: 15, fontWeight: '600', marginTop: 5 }, heading: { color: colors.text, fontSize: 18, fontWeight: '700', marginBottom: 8 }, filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, filter: { color: colors.blue, backgroundColor: '#141E37', borderRadius: radius.pill, paddingHorizontal: 13, paddingVertical: 8, fontWeight: '700' } });
