import { useState } from "react";
import { Alert, Pressable, Text, View } from "react-native";
import { Button, Card, Header, Input, Screen, SectionHeader, uiStyles } from "@/components/ui";
import { useAppData } from "@/context/AppDataContext";
import { CalibrationFrameType } from "@/types";
import { createThemedStyles, radius, spacing } from "@/theme";

const types: CalibrationFrameType[] = ["Dark", "Flat", "Bias", "Dark flat"];
export default function CalibrationLibraryScreen() {
  const { calibrationFrames, saveCalibrationFrameSet, deleteCalibrationFrameSet, equipment } = useAppData(); const [type, setType] = useState<CalibrationFrameType>("Dark"); const [camera, setCamera] = useState(equipment.cameras[0]?.name ?? ""); const [gain, setGain] = useState("100"); const [exposure, setExposure] = useState("300"); const [temperature, setTemperature] = useState("-10"); const [filter, setFilter] = useState(""); const [count, setCount] = useState("30");
  const save = async () => { await saveCalibrationFrameSet({ id: `cal-${Date.now()}`, type, camera: camera.trim() || "Unknown camera", gain: Number(gain) || 0, exposureSeconds: Number(exposure) || 0, temperatureCelsius: temperature.trim() ? Number(temperature) : null, binning: 1, filter: filter.trim(), frameCount: Number(count) || 1, createdAt: new Date().toISOString(), notes: "" }); };
  const warnings = calibrationFrames.length ? [] : ["No calibration masters recorded yet"];
  return <Screen><Header eyebrow="Master-frame inventory" title="Calibration Library" />{warnings.map((warning) => <Card key={warning} style={styles.warning}><Text style={styles.warningText}>{warning}</Text></Card>)}<SectionHeader title="Record a frame set" /><View style={styles.chips}>{types.map((item) => <Pressable key={item} onPress={() => setType(item)} style={[styles.chip, type === item && styles.active]}><Text style={[styles.chipText, type === item && styles.activeText]}>{item}</Text></Pressable>)}</View><Card><Input label="Camera" value={camera} onChangeText={setCamera} /><View style={styles.row}><View style={{ flex: 1 }}><Input label="Gain" value={gain} onChangeText={setGain} keyboardType="number-pad" /></View><View style={{ flex: 1 }}><Input label="Exposure (s)" value={exposure} onChangeText={setExposure} keyboardType="decimal-pad" /></View></View><View style={styles.row}><View style={{ flex: 1 }}><Input label="Temperature °C" value={temperature} onChangeText={setTemperature} keyboardType="numbers-and-punctuation" /></View><View style={{ flex: 1 }}><Input label="Frame count" value={count} onChangeText={setCount} keyboardType="number-pad" /></View></View><Input label="Filter (for flats)" value={filter} onChangeText={setFilter} /><Button title="Add to calibration library" onPress={() => void save()} /></Card><SectionHeader title="Saved calibration sets" subtitle={`${calibrationFrames.length} combinations tracked`} />{calibrationFrames.map((item) => <Card key={item.id}><View style={styles.row}><View style={{ flex: 1 }}><Text style={styles.type}>{item.type}</Text><Text style={uiStyles.h3}>{item.camera}</Text><Text style={uiStyles.muted}>Gain {item.gain} · {item.exposureSeconds}s · {item.temperatureCelsius == null ? "uncooled" : `${item.temperatureCelsius}°C`} · {item.frameCount} frames{item.filter ? ` · ${item.filter}` : ""}</Text></View><Pressable onPress={() => Alert.alert("Delete calibration set?", "This removes the inventory record, not any image files.", [{ text: "Cancel", style: "cancel" }, { text: "Delete", style: "destructive", onPress: () => void deleteCalibrationFrameSet(item.id) }])}><Text style={styles.delete}>Delete</Text></Pressable></View></Card>)}
  </Screen>;
}
const styles = createThemedStyles((colors) => ({ warning: { borderColor: colors.warning }, warningText: { color: colors.warning, fontWeight: "800" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: spacing.xs }, chip: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: 13, paddingVertical: 9 }, active: { backgroundColor: colors.gold }, chipText: { color: colors.text, fontWeight: "700" }, activeText: { color: colors.background }, row: { flexDirection: "row", gap: spacing.sm, alignItems: "center" }, type: { color: colors.gold, fontWeight: "900", letterSpacing: 1 }, delete: { color: colors.danger, fontWeight: "800" } }));
