import { useState } from "react";
import * as DocumentPicker from "expo-document-picker";
import { File } from "expo-file-system";
import { Text, View } from "react-native";
import { Button, Card, ErrorBanner, Header, Screen, SectionHeader, uiStyles } from "@/components/ui";
import { AstroFileInspection, inspectAstroFile } from "@/utils/astroFiles";
import { createThemedStyles, spacing } from "@/theme";

export default function FileInspectorScreen() {
  const [result, setResult] = useState<AstroFileInspection | null>(null); const [name, setName] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const choose = async () => { setError(""); const picked = await DocumentPicker.getDocumentAsync({ type: "*/*", copyToCacheDirectory: true }); if (picked.canceled) return; const asset = picked.assets[0]; setBusy(true); try { const bytes = await new File(asset.uri).bytes(); setResult(inspectAstroFile(bytes, asset.name)); setName(asset.name); } catch (reason) { setError(reason instanceof Error ? reason.message : "This file could not be inspected."); } finally { setBusy(false); } };
  return <Screen><Header eyebrow="Raw subframe diagnostics" title="FITS / XISF Inspector" /><Text style={uiStyles.muted}>Open a raw astronomy file locally. AstroToolkit reads its header and supported FITS pixel samples without uploading or modifying the original.</Text>{error ? <ErrorBanner message={error} /> : null}<Button title={busy ? "Reading astronomy file…" : "Choose FITS or XISF file"} onPress={() => void choose()} disabled={busy} />
    {result ? <><Card style={styles.hero}><Text style={styles.format}>{result.format}</Text><Text style={styles.name}>{name}</Text><Text style={uiStyles.muted}>{result.width ?? "?"} × {result.height ?? "?"} · {result.channels ?? "?"} channel(s) · {result.bitDepth}</Text></Card><SectionHeader title="Capture metadata" /><View style={styles.grid}><Metric label="OBJECT" value={result.object ?? "Not recorded"} /><Metric label="FILTER" value={result.filter ?? "Not recorded"} /><Metric label="EXPOSURE" value={result.exposureSeconds == null ? "—" : `${result.exposureSeconds}s`} /><Metric label="GAIN" value={result.gain == null ? "—" : `${result.gain}`} /><Metric label="TEMPERATURE" value={result.temperature == null ? "—" : `${result.temperature}°C`} /><Metric label="DATE OBSERVED" value={result.dateObserved ?? "Not recorded"} /></View><SectionHeader title="Pixel and star sample" />{result.histogram ? <Card><View style={styles.histogram}>{result.histogram.map((value, index) => <View key={index} style={[styles.histogramBar, { height: `${Math.max(2, (value / Math.max(...result.histogram!)) * 100)}%` }]} />)}</View></Card> : null}<View style={styles.grid}><Metric label="MINIMUM" value={result.minimum?.toFixed(1) ?? "—"} /><Metric label="MEDIAN" value={result.median?.toFixed(1) ?? "—"} /><Metric label="MAXIMUM" value={result.maximum?.toFixed(1) ?? "—"} /><Metric label="STARS" value={result.starCount?.toString() ?? "—"} /><Metric label="FWHM" value={result.fwhmPixels == null ? "—" : `${result.fwhmPixels.toFixed(2)} px`} /><Metric label="ECCENTRICITY" value={result.eccentricity?.toFixed(2) ?? "—"} /></View><Card>{result.notes.map((note) => <Text key={note} style={uiStyles.body}>• {note}</Text>)}</Card></> : null}
  </Screen>;
}
function Metric({ label, value }: { label: string; value: string }) { return <Card style={styles.metric}><Text style={styles.label}>{label}</Text><Text style={styles.value}>{value}</Text></Card>; }
const styles = createThemedStyles((colors) => ({ hero: { borderColor: colors.gold }, format: { color: colors.gold, fontWeight: "900", letterSpacing: 1.3 }, name: { color: colors.text, fontSize: 20, fontWeight: "800" }, grid: { flexDirection: "row", flexWrap: "wrap", gap: spacing.sm }, metric: { width: "47%", flexGrow: 1 }, label: { color: colors.muted, fontSize: 9, fontWeight: "900" }, value: { color: colors.text, fontSize: 15, fontWeight: "700" }, histogram: { height: 120, flexDirection: "row", alignItems: "flex-end", gap: 3 }, histogramBar: { flex: 1, backgroundColor: colors.gold, borderRadius: 2 } }));
