import { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Button, Card, Header, Input, Screen, SectionHeader, uiStyles } from '@/components/ui';
import { fieldOfView, pixelScale } from '@/utils/calculations';
import { colors, spacing } from '@/theme';

type Field = 'focalLength' | 'sensorWidth' | 'sensorHeight' | 'pixelSize' | 'resolutionWidth' | 'resolutionHeight';
const initial: Record<Field, string> = { focalLength: '', sensorWidth: '', sensorHeight: '', pixelSize: '', resolutionWidth: '', resolutionHeight: '' };
export default function CalculateScreen() {
  const [values, setValues] = useState(initial); const [errors, setErrors] = useState<Partial<Record<Field, string>>>({}); const [result, setResult] = useState<{ horizontal: number; vertical: number; scale: number } | null>(null);
  const set = (field: Field, value: string) => { setValues((current) => ({ ...current, [field]: value })); setErrors((current) => ({ ...current, [field]: undefined })); };
  const calculate = () => { const nextErrors: Partial<Record<Field, string>> = {}; (Object.keys(values) as Field[]).forEach((key) => { const value = Number(values[key]); if (!values[key].trim()) nextErrors[key] = 'Required'; else if (!Number.isFinite(value) || value <= 0) nextErrors[key] = 'Enter a number greater than zero'; else if ((key === 'resolutionWidth' || key === 'resolutionHeight') && !Number.isInteger(value)) nextErrors[key] = 'Use a whole pixel count'; }); setErrors(nextErrors); if (Object.keys(nextErrors).length) { setResult(null); return; } const focal = Number(values.focalLength); setResult({ horizontal: fieldOfView(Number(values.sensorWidth), focal), vertical: fieldOfView(Number(values.sensorHeight), focal), scale: pixelScale(Number(values.pixelSize), focal) }); };
  const reset = () => { setValues(initial); setErrors({}); setResult(null); };
  return <Screen><Header eyebrow="Optical planning" title="Calculate" /><SectionHeader title="Field of view & pixel scale" subtitle="Enter your telescope and camera specifications" /><Card><Input label="Telescope focal length (mm)" keyboardType="decimal-pad" value={values.focalLength} onChangeText={(v) => set('focalLength', v)} error={errors.focalLength} placeholder="e.g. 480" /><View style={styles.two}><View style={styles.half}><Input label="Sensor width (mm)" keyboardType="decimal-pad" value={values.sensorWidth} onChangeText={(v) => set('sensorWidth', v)} error={errors.sensorWidth} placeholder="23.5" /></View><View style={styles.half}><Input label="Sensor height (mm)" keyboardType="decimal-pad" value={values.sensorHeight} onChangeText={(v) => set('sensorHeight', v)} error={errors.sensorHeight} placeholder="15.7" /></View></View><Input label="Pixel size (microns)" keyboardType="decimal-pad" value={values.pixelSize} onChangeText={(v) => set('pixelSize', v)} error={errors.pixelSize} placeholder="3.76" /><View style={styles.two}><View style={styles.half}><Input label="Resolution width (px)" keyboardType="number-pad" value={values.resolutionWidth} onChangeText={(v) => set('resolutionWidth', v)} error={errors.resolutionWidth} placeholder="6248" /></View><View style={styles.half}><Input label="Resolution height (px)" keyboardType="number-pad" value={values.resolutionHeight} onChangeText={(v) => set('resolutionHeight', v)} error={errors.resolutionHeight} placeholder="4176" /></View></View><Button title="Calculate framing" onPress={calculate} /><Button title="Reset" variant="secondary" onPress={reset} /></Card>{result ? <><SectionHeader title="Your imaging frame" /><View style={styles.results}><Result label="HORIZONTAL FOV" value={`${result.horizontal.toFixed(2)}°`} text="The sky width captured across the sensor." /><Result label="VERTICAL FOV" value={`${result.vertical.toFixed(2)}°`} text="The sky height captured across the sensor." /><Result label="PIXEL SCALE" value={`${result.scale.toFixed(2)}″/px`} text="Angular sky detail recorded by each pixel." /></View><Card><Text style={styles.noteTitle}>How to read this</Text><Text style={uiStyles.muted}>A larger field of view fits wider targets. Pixel scale near 1–2 arcseconds per pixel is a versatile starting point, though ideal sampling depends on seeing and optics.</Text></Card></> : null}</Screen>;
}
function Result({ label, value, text }: { label: string; value: string; text: string }) { return <Card style={styles.result}><Text style={styles.resultLabel}>{label}</Text><Text style={styles.resultValue}>{value}</Text><Text style={uiStyles.muted}>{text}</Text></Card>; }
const styles = StyleSheet.create({ two: { flexDirection: 'row', gap: spacing.sm }, half: { flex: 1 }, results: { gap: spacing.sm }, result: { borderLeftColor: colors.gold, borderLeftWidth: 3 }, resultLabel: { color: colors.muted, fontSize: 10, fontWeight: '800', letterSpacing: 1.2 }, resultValue: { color: colors.gold, fontSize: 28, fontWeight: '700' }, noteTitle: { color: colors.text, fontSize: 16, fontWeight: '700' } });
