import { useMemo, useState } from 'react';
import { useRouter } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Card, EmptyState, Header, Screen, SectionHeader, uiStyles } from '@/components/ui';
import { targets } from '@/data/targets';
import { TargetType } from '@/types';
import { colors, radius, spacing } from '@/theme';

const filters: { label: string; value: TargetType | 'All' }[] = [{ label: 'All', value: 'All' }, { label: 'Nebulae', value: 'Nebula' }, { label: 'Galaxies', value: 'Galaxy' }, { label: 'Clusters', value: 'Cluster' }, { label: 'Planetary', value: 'Planetary Nebula' }];
export default function CatalogueScreen() {
  const router = useRouter(); const [query, setQuery] = useState(''); const [filter, setFilter] = useState<TargetType | 'All'>('All');
  const results = useMemo(() => targets.filter((target) => (filter === 'All' || target.type === filter) && `${target.name} ${target.identifiers.join(' ')} ${target.constellation}`.toLowerCase().includes(query.trim().toLowerCase())), [filter, query]);
  return <Screen><Header eyebrow="Deep-sky atlas" title="Catalogue" /><View style={styles.search}><Text style={styles.searchIcon}>⌕</Text><TextInput value={query} onChangeText={setQuery} placeholder="Search targets, catalogues…" placeholderTextColor={colors.muted} style={styles.searchInput} /></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map((item) => <Pressable key={item.value} onPress={() => setFilter(item.value)} style={[styles.chip, filter === item.value && styles.chipActive]}><Text style={[styles.chipText, filter === item.value && styles.chipTextActive]}>{item.label}</Text></Pressable>)}</ScrollView><SectionHeader title={`${results.length} deep-sky objects`} subtitle="Tap a target for coordinates and imaging notes" />{results.length === 0 ? <EmptyState title="No targets found" message="Try another search or choose a different object type." /> : results.map((target) => <Pressable key={target.id} onPress={() => router.push(`/catalogue/${target.id}`)}><Card style={styles.target}><View style={styles.objectMark}><Text style={styles.objectMarkText}>✦</Text></View><View style={{ flex: 1 }}><Text style={styles.catalogue}>{target.catalogue} · {target.type}</Text><Text style={uiStyles.h3}>{target.name}</Text><Text style={uiStyles.muted}>{target.constellation} · {target.difficulty}</Text></View><Text style={styles.chevron}>›</Text></Card></Pressable>)}</Screen>;
}
const styles = StyleSheet.create({ search: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.input, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, paddingHorizontal: 14 }, searchIcon: { color: colors.gold, fontSize: 24 }, searchInput: { flex: 1, color: colors.text, fontSize: 16, padding: 14 }, filters: { gap: spacing.sm }, chip: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: 15, paddingVertical: 10 }, chipActive: { backgroundColor: colors.gold, borderColor: colors.gold }, chipText: { color: colors.muted, fontWeight: '600' }, chipTextActive: { color: colors.background }, target: { flexDirection: 'row', alignItems: 'center' }, objectMark: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#171F33', alignItems: 'center', justifyContent: 'center' }, objectMarkText: { color: colors.gold, fontSize: 18 }, catalogue: { color: colors.gold, fontSize: 11, fontWeight: '700' }, chevron: { color: colors.muted, fontSize: 28 } });
