import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, View } from 'react-native';
import { Button, Card, EmptyState, ErrorBanner, Header, Input, LoadingState, Screen, SectionHeader, uiStyles } from '@/components/ui';
import { useAppData } from '@/context/AppDataContext';
import { AstroFilter, Camera, EquipmentState, ImagingRig, Telescope } from '@/types';
import { colors, radius, spacing } from '@/theme';

type Kind = 'telescopes' | 'cameras' | 'filters' | 'rigs';
type Draft = { kind: Kind; id?: string; name: string; aperture: string; focalLength: string; focalRatio: string; sensorWidth: string; sensorHeight: string; pixelSize: string; resolutionWidth: string; resolutionHeight: string; filterType: string; bandwidth: string; telescopeId: string; cameraId: string; filterIds: string[] };
const blank = (kind: Kind): Draft => ({ kind, name: '', aperture: '', focalLength: '', focalRatio: '', sensorWidth: '', sensorHeight: '', pixelSize: '', resolutionWidth: '', resolutionHeight: '', filterType: '', bandwidth: '', telescopeId: '', cameraId: '', filterIds: [] });
const labels: Record<Kind, string> = { telescopes: 'Telescope', cameras: 'Camera', filters: 'Filter', rigs: 'Imaging rig' };

export default function EquipmentScreen() {
  const { equipment, saveEquipment, loading, error } = useAppData(); const [draft, setDraft] = useState<Draft | null>(null); const [errors, setErrors] = useState<Record<string, string>>({});
  if (loading) return <Screen><Header eyebrow="Your observatory" title="Equipment" /><LoadingState /></Screen>;
  const field = (key: keyof Draft, value: string | string[]) => draft && setDraft({ ...draft, [key]: value });
  const submit = async () => { if (!draft) return; const next: Record<string, string> = {}; if (!draft.name.trim()) next.name = 'Name is required'; const required: (keyof Draft)[] = draft.kind === 'telescopes' ? ['aperture','focalLength','focalRatio'] : draft.kind === 'cameras' ? ['sensorWidth','sensorHeight','pixelSize','resolutionWidth','resolutionHeight'] : draft.kind === 'filters' ? ['filterType','bandwidth'] : ['telescopeId','cameraId']; required.forEach((key) => { const value = draft[key]; if (!String(value).trim()) next[String(key)] = 'Required'; else if (!['filterType','telescopeId','cameraId'].includes(String(key)) && (!Number.isFinite(Number(value)) || Number(value) <= 0)) next[String(key)] = 'Enter a positive number'; }); if (draft.kind === 'cameras' && (!Number.isInteger(Number(draft.resolutionWidth)) || !Number.isInteger(Number(draft.resolutionHeight)))) next.resolutionWidth = 'Resolution must use whole pixels'; setErrors(next); if (Object.keys(next).length) return; const id = draft.id ?? `${draft.kind}-${Date.now()}`; let state: EquipmentState = equipment; if (draft.kind === 'telescopes') { const item: Telescope = { id, name: draft.name.trim(), aperture: Number(draft.aperture), focalLength: Number(draft.focalLength), focalRatio: Number(draft.focalRatio) }; state = { ...equipment, telescopes: upsert(equipment.telescopes, item) }; } if (draft.kind === 'cameras') { const item: Camera = { id, name: draft.name.trim(), sensorWidth: Number(draft.sensorWidth), sensorHeight: Number(draft.sensorHeight), pixelSize: Number(draft.pixelSize), resolutionWidth: Number(draft.resolutionWidth), resolutionHeight: Number(draft.resolutionHeight) }; state = { ...equipment, cameras: upsert(equipment.cameras, item) }; } if (draft.kind === 'filters') { const item: AstroFilter = { id, name: draft.name.trim(), filterType: draft.filterType.trim(), bandwidth: Number(draft.bandwidth) }; state = { ...equipment, filters: upsert(equipment.filters, item) }; } if (draft.kind === 'rigs') { const item: ImagingRig = { id, name: draft.name.trim(), telescopeId: draft.telescopeId, cameraId: draft.cameraId, filterIds: draft.filterIds }; state = { ...equipment, rigs: upsert(equipment.rigs, item) }; } await saveEquipment(state); setDraft(null); setErrors({}); };
  const remove = (kind: Kind, id: string, name: string) => Alert.alert(`Delete ${labels[kind].toLowerCase()}?`, `${name} will be removed from this device.`, [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => { let next: EquipmentState = { ...equipment, [kind]: equipment[kind].filter((item) => item.id !== id) }; if (kind === 'telescopes') next.rigs = next.rigs.filter((rig) => rig.telescopeId !== id); if (kind === 'cameras') next.rigs = next.rigs.filter((rig) => rig.cameraId !== id); if (kind === 'filters') next.rigs = next.rigs.map((rig) => ({ ...rig, filterIds: rig.filterIds.filter((filterId) => filterId !== id) })); void saveEquipment(next); } }]);
  const edit = (kind: Kind, item: Telescope | Camera | AstroFilter | ImagingRig) => { const base = blank(kind); if (kind === 'telescopes') { const i = item as Telescope; setDraft({ ...base, id: i.id, name: i.name, aperture: String(i.aperture), focalLength: String(i.focalLength), focalRatio: String(i.focalRatio) }); } if (kind === 'cameras') { const i = item as Camera; setDraft({ ...base, id: i.id, name: i.name, sensorWidth: String(i.sensorWidth), sensorHeight: String(i.sensorHeight), pixelSize: String(i.pixelSize), resolutionWidth: String(i.resolutionWidth), resolutionHeight: String(i.resolutionHeight) }); } if (kind === 'filters') { const i = item as AstroFilter; setDraft({ ...base, id: i.id, name: i.name, filterType: i.filterType, bandwidth: String(i.bandwidth) }); } if (kind === 'rigs') { const i = item as ImagingRig; setDraft({ ...base, id: i.id, name: i.name, telescopeId: i.telescopeId, cameraId: i.cameraId, filterIds: i.filterIds }); } };
  return <Screen><Header eyebrow="Your observatory" title="Equipment" />{error ? <ErrorBanner message={error} /> : null}{draft ? <EquipmentForm draft={draft} errors={errors} equipment={equipment} setField={field} submit={() => void submit()} cancel={() => { setDraft(null); setErrors({}); }} /> : <>{(['telescopes','cameras','filters','rigs'] as Kind[]).map((kind) => <View key={kind} style={styles.section}><SectionHeader title={kind === 'rigs' ? 'Imaging rigs' : kind[0].toUpperCase() + kind.slice(1)} subtitle={kind === 'rigs' ? 'Combine your optical train' : `${equipment[kind].length} saved`} action={<Pressable onPress={() => setDraft(blank(kind))}><Text style={styles.add}>＋ Add</Text></Pressable>} />{equipment[kind].length === 0 ? <EmptyState title={`No ${kind} yet`} message={`Add your first ${labels[kind].toLowerCase()} to start building your setup.`} /> : equipment[kind].map((item) => <EquipmentCard key={item.id} kind={kind} item={item} equipment={equipment} onEdit={() => edit(kind, item)} onDelete={() => remove(kind, item.id, item.name)} />)}</View>)}</>}</Screen>;
}

function EquipmentForm({ draft, errors, equipment, setField, submit, cancel }: { draft: Draft; errors: Record<string,string>; equipment: EquipmentState; setField: (key: keyof Draft, value: string | string[]) => void; submit: () => void; cancel: () => void }) {
  const number = (label: string, key: keyof Draft, placeholder?: string) => <Input label={label} value={String(draft[key])} keyboardType="decimal-pad" onChangeText={(v) => setField(key, v)} error={errors[String(key)]} placeholder={placeholder} />;
  return <><SectionHeader title={`${draft.id ? 'Edit' : 'Add'} ${labels[draft.kind].toLowerCase()}`} subtitle="All specifications are stored locally" /><Card><Input label={draft.kind === 'rigs' ? 'Rig name' : 'Name'} value={draft.name} onChangeText={(v) => setField('name', v)} error={errors.name} placeholder={`My ${labels[draft.kind].toLowerCase()}`} />{draft.kind === 'telescopes' ? <>{number('Aperture (mm)','aperture','80')}{number('Focal length (mm)','focalLength','480')}{number('Focal ratio','focalRatio','6')}</> : null}{draft.kind === 'cameras' ? <>{number('Sensor width (mm)','sensorWidth','23.5')}{number('Sensor height (mm)','sensorHeight','15.7')}{number('Pixel size (microns)','pixelSize','3.76')}{number('Resolution width (px)','resolutionWidth','6248')}{number('Resolution height (px)','resolutionHeight','4176')}</> : null}{draft.kind === 'filters' ? <><Input label="Filter type" value={draft.filterType} onChangeText={(v) => setField('filterType', v)} error={errors.filterType} placeholder="e.g. Ha, OIII or Dual band" />{number('Bandwidth (nm)','bandwidth','7')}</> : null}{draft.kind === 'rigs' ? <><Choice label="Telescope" items={equipment.telescopes} selected={[draft.telescopeId]} error={errors.telescopeId} onPress={(id) => setField('telescopeId', id)} /><Choice label="Camera" items={equipment.cameras} selected={[draft.cameraId]} error={errors.cameraId} onPress={(id) => setField('cameraId', id)} /><Choice label="Filters (choose multiple)" items={equipment.filters} selected={draft.filterIds} onPress={(id) => setField('filterIds', draft.filterIds.includes(id) ? draft.filterIds.filter((value) => value !== id) : [...draft.filterIds, id])} /></> : null}<Button title={draft.id ? 'Save changes' : `Add ${labels[draft.kind].toLowerCase()}`} onPress={submit} /><Button title="Cancel" variant="secondary" onPress={cancel} /></Card></>;
}
function Choice({ label, items, selected, error, onPress }: { label: string; items: { id: string; name: string }[]; selected: string[]; error?: string; onPress: (id: string) => void }) { return <View style={{ gap: spacing.xs }}><Text style={styles.label}>{label}</Text>{items.length ? <View style={styles.choices}>{items.map((item) => <Pressable key={item.id} onPress={() => onPress(item.id)} style={[styles.choice, selected.includes(item.id) && styles.choiceActive]}><Text style={[styles.choiceText, selected.includes(item.id) && styles.choiceTextActive]}>{item.name}</Text></Pressable>)}</View> : <Text style={styles.error}>Add compatible equipment first.</Text>}{error ? <Text style={styles.error}>{error}</Text> : null}</View>; }
function EquipmentCard({ kind, item, equipment, onEdit, onDelete }: { kind: Kind; item: Telescope | Camera | AstroFilter | ImagingRig; equipment: EquipmentState; onEdit: () => void; onDelete: () => void }) { let detail = ''; if (kind === 'telescopes') { const i = item as Telescope; detail = `${i.aperture}mm aperture · ${i.focalLength}mm · f/${i.focalRatio}`; } if (kind === 'cameras') { const i = item as Camera; detail = `${i.sensorWidth} × ${i.sensorHeight}mm · ${i.pixelSize}μm · ${i.resolutionWidth} × ${i.resolutionHeight}`; } if (kind === 'filters') { const i = item as AstroFilter; detail = `${i.filterType} · ${i.bandwidth}nm bandwidth`; } if (kind === 'rigs') { const i = item as ImagingRig; const scope = equipment.telescopes.find((x) => x.id === i.telescopeId)?.name ?? 'Missing telescope'; const camera = equipment.cameras.find((x) => x.id === i.cameraId)?.name ?? 'Missing camera'; const filters = i.filterIds.map((id) => equipment.filters.find((x) => x.id === id)?.name).filter(Boolean).join(', ') || 'No filters'; detail = `${scope} · ${camera}\n${filters}`; } return <Card><View style={styles.itemHead}><View style={{ flex: 1 }}><Text style={uiStyles.h3}>{item.name}</Text><Text style={uiStyles.muted}>{detail}</Text></View><View style={styles.typeIcon}><Text style={styles.typeIconText}>{kind === 'telescopes' ? '⌕' : kind === 'cameras' ? '▣' : kind === 'filters' ? '◉' : '⌾'}</Text></View></View><View style={styles.actions}><View style={{ flex: 1 }}><Button title="Edit" variant="secondary" onPress={onEdit} /></View><View style={{ flex: 1 }}><Button title="Delete" variant="danger" onPress={onDelete} /></View></View></Card>; }
function upsert<T extends { id: string }>(items: T[], item: T): T[] { return items.some((current) => current.id === item.id) ? items.map((current) => current.id === item.id ? item : current) : [item, ...items]; }
const styles = StyleSheet.create({ section: { gap: spacing.md }, add: { color: colors.gold, fontWeight: '700', fontSize: 15 }, label: { color: colors.text, fontSize: 14, fontWeight: '600' }, choices: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, choice: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingHorizontal: 12, paddingVertical: 8 }, choiceActive: { backgroundColor: colors.gold, borderColor: colors.gold }, choiceText: { color: colors.muted, fontWeight: '600' }, choiceTextActive: { color: colors.background }, error: { color: colors.danger, fontSize: 13 }, itemHead: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, typeIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: colors.input, alignItems: 'center', justifyContent: 'center' }, typeIconText: { color: colors.gold, fontSize: 20 }, actions: { flexDirection: 'row', gap: spacing.sm } });
