import { useMemo } from 'react';
import { Href, useRouter } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Card, ErrorBanner, Header, Screen, SectionHeader, uiStyles } from '@/components/ui';
import { targets } from '@/data/targets';
import { useAppData } from '@/context/AppDataContext';
import { bestTargetsTonight, moonPhase } from '@/utils/astronomy';
import { colors, radius, spacing } from '@/theme';

function coordinate(value: number, positive: string, negative: string) { return `${Math.abs(value).toFixed(2)}°${value >= 0 ? positive : negative}`; }

export default function TonightScreen() {
  const router = useRouter(); const { favourites, toggleFavourite, observer, error } = useAppData(); const reference = useMemo(() => new Date(), []);
  const recommendations = useMemo(() => bestTargetsTonight(targets, observer, reference), [observer, reference]);
  const moon = useMemo(() => moonPhase(reference), [reference]);
  const date = new Intl.DateTimeFormat('en-GB', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(reference);
  return <Screen><Header eyebrow="Plan the night" onSettings={() => router.push('/about')} /><View><Text style={styles.date}>{date}</Text><Text style={uiStyles.muted}>Recommendations update for your observing site</Text></View>{error ? <ErrorBanner message={error} /> : null}
    <Pressable onPress={() => router.push('/location' as Href)}><Card style={styles.locationCard}><View style={styles.pin}><Text style={styles.pinText}>⌖</Text></View><View style={{ flex: 1 }}><Text style={styles.kicker}>OBSERVING FROM</Text><Text style={styles.locationName}>{observer.label}</Text><Text style={uiStyles.muted}>{coordinate(observer.latitude, 'N', 'S')} · {coordinate(observer.longitude, 'E', 'W')}</Text></View><Text style={styles.change}>{observer.source === 'default' ? 'Set up ›' : 'Change ›'}</Text></Card></Pressable>
    <Card style={styles.moon}><View style={styles.moonIcon}><Text style={styles.moonGlyph}>☾</Text></View><View style={{ flex: 1 }}><Text style={styles.kicker}>MOON TONIGHT</Text><Text style={uiStyles.h3}>{moon.name} · {moon.illumination}%</Text><Text style={uiStyles.muted}>Estimated illuminated fraction</Text></View><View style={[styles.rating, moon.rating === 'BRIGHT' && styles.ratingBright]}><Text style={[styles.ratingText, moon.rating === 'BRIGHT' && styles.ratingBrightText]}>{moon.rating}</Text></View></Card>
    <SectionHeader title="Best targets tonight" subtitle="Ranked by peak altitude between 18:00 and 06:00" />
    {recommendations.map(({ target, currentAltitude, maximumAltitude, bestTime }) => <Pressable key={target.id} onPress={() => router.push(`/catalogue/${target.id}`)}><Card><View style={styles.targetHead}><View style={{ flex: 1 }}><Text style={styles.catalogue}>{target.catalogue} · {target.type}</Text><Text style={uiStyles.h3}>{target.name}</Text><Text style={uiStyles.muted}>{target.constellation}</Text></View><Pressable accessibilityLabel={`${favourites.includes(target.id) ? 'Remove' : 'Add'} ${target.name} favourite`} hitSlop={12} onPress={() => void toggleFavourite(target.id)}><Text style={[styles.star, favourites.includes(target.id) && styles.starActive]}>★</Text></Pressable></View><View style={styles.stats}><Stat label="ALTITUDE NOW" value={`${Math.round(currentAltitude)}°`} /><Stat label="PEAK TONIGHT" value={`${Math.round(maximumAltitude)}°`} /><Stat label="BEST TIME" value={bestTime} /></View><View style={styles.filters}>{target.filters.map((filter) => <Text key={filter} style={styles.filter}>{filter}</Text>)}</View></Card></Pressable>)}
    <Text style={styles.disclaimer}>Visibility is an astronomical estimate. Local terrain, buildings, weather and twilight are not included.</Text>
  </Screen>;
}
function Stat({ label, value }: { label: string; value: string }) { return <View style={{ flex: 1 }}><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ date: { color: colors.text, fontSize: 17, fontWeight: '600', marginBottom: 4 }, locationCard: { flexDirection: 'row', alignItems: 'center', borderColor: colors.gold }, pin: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#282318', alignItems: 'center', justifyContent: 'center' }, pinText: { color: colors.gold, fontSize: 23 }, locationName: { color: colors.text, fontSize: 16, fontWeight: '700' }, change: { color: colors.gold, fontWeight: '700', fontSize: 13 }, moon: { flexDirection: 'row', alignItems: 'center', paddingVertical: 20 }, moonIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: '#1B2336', alignItems: 'center', justifyContent: 'center' }, moonGlyph: { color: colors.gold, fontSize: 33 }, kicker: { color: colors.gold, fontSize: 10, fontWeight: '800', letterSpacing: 1.4 }, rating: { backgroundColor: '#173328', borderRadius: radius.pill, paddingHorizontal: 9, paddingVertical: 6 }, ratingText: { color: colors.success, fontSize: 9, fontWeight: '800' }, ratingBright: { backgroundColor: '#382E18' }, ratingBrightText: { color: colors.warning }, targetHead: { flexDirection: 'row' }, catalogue: { color: colors.gold, fontSize: 12, fontWeight: '700', marginBottom: 4 }, star: { color: colors.border, fontSize: 25 }, starActive: { color: colors.gold }, stats: { flexDirection: 'row', gap: spacing.xs, backgroundColor: colors.input, padding: 12, borderRadius: radius.md }, statLabel: { color: colors.muted, fontSize: 8, fontWeight: '700', letterSpacing: 0.6 }, statValue: { color: colors.text, fontSize: 12, fontWeight: '600', marginTop: 4 }, filters: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs }, filter: { color: colors.blue, backgroundColor: '#141E37', borderRadius: radius.pill, paddingHorizontal: 9, paddingVertical: 5, fontSize: 11, fontWeight: '700' }, disclaimer: { color: colors.muted, fontSize: 11, lineHeight: 16, textAlign: 'center' } });
